// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/21/2025, 10:36:17 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/plugins/**/*.{js,ts,mjs}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/composables/**/*.{js,ts,mjs}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/utils/**/*.{js,ts,mjs}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/francescgimenezgil/iCloud Drive (Archive)/Documents/projects/dogfy-form/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;